version: "3.8"
services:
  gateway:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./configs/nginx/conf.d/:/etc/nginx/conf.d/
  admiralis-db:
    image: mongo
    restart: unless-stopped
    container_name: admiralis-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: rootdb
    volumes:
      - admiralis-db:/data
  ms-computer:
    container_name: ms-computer
    image: 0hmygoat/ms-computer:main
    depends_on:
      - admiralis-db
    ports:
      - "8081:8081"
  ms-course:
    container_name: ms-course
    image: 0hmygoat/ms-course:main
    depends_on:
      - admiralis-db
    ports:
      - "8080:8080"
  ms-loan:
    container_name: ms-loan
    image: 0hmygoat/ms-loan:main
    depends_on:
      - admiralis-db
      - ms-computer
      - ms-course
    ports:
      - "8082:8080"
volumes:
  admiralis-db: