version: "3.8"
services:
  gateway:
    image: nginx
    container_name: gateway
    ports:
      - '80:80'
    volumes:
      - ./configs/nginx/conf.d/:/etc/nginx/conf.d/
      - './configs/nginx/ssl/:/etc/nginx/ssl/'
    depends_on:
      - ms-computer
      - ms-course
      - ms-loan
      - admiralis-db
  admiralis-db:
    image: mongo
    restart: unless-stopped
    container_name: admiralis-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: rootdb
    volumes:
      - admiralis-db:/data
  ms-computer:
    container_name: ms-computer
    image: 0hmygoat/ms-computer:main
    depends_on:
      - admiralis-db
  ms-course:
    container_name: ms-course
    image: 0hmygoat/ms-course:main
    depends_on:
      - admiralis-db
  ms-loan:
    container_name: ms-loan
    image: 0hmygoat/ms-loan:main
    depends_on:
      - admiralis-db
      - ms-computer
      - ms-course
  front-web:
    container_name: frontend
    image: 0hmygoat/front-web:main
volumes:
  admiralis-db: